### ISSUE TITLE
How to generate a truly valid key?

### ISSUE THREAD

**Issue by WestDvina** [awuctl/licensing-stuff#2]
Hi. I tried to generate a key.
In PIG Key Checker, it passes the test, it does not work on Windows to activate it. I also used the pc config files attached to the script from my own system.
How to generate a truly valid key?
Thanks!
————————————
Windows 10 PRO 22H2 x64

**Comment by awuctl** [comment]
You can't.
These keys are not usable for activation unless you somehow happen to correctly guess the [security](https://github.com/awuctl/licensing-stuff/blob/main/docs/details.md#secret) value

Your chance of guessing correctly is just a tiny bit over one in ten quadrillion.
